### ISSUE TITLE
Not all purifiers load when restarting HA

### ISSUE THREAD

**Issue by ludipq** [betaboon/philips-airpurifier#12]
I have integrated 3x AC1214 and when I restart Home Assistant, it's pretty random if they all come up or not. Sometimes they all load fine, the next restart only one of them load and the other two are unavailable, the next restart all 3 are unavailable etc.

**Comment by barbatron** [comment]
My 1214 also takes somewhere between 8 and 30 minutes (typically ~10) to pop back from "unavailable" after HA restart.

**Comment by ludipq** [comment]
Well, the longest I have tested so far is 2 hours, still not up.

**Comment by ludipq** [comment]
Now they won't load at all, either of them. No matter how many times I restart :(

**Comment by djanosz** [comment]
What does your configuration look like, I can't add. second purifier. I will be grateful for your help.

**Comment by ludipq** [comment]
> What does your configuration look like, I can't add. second purifier. I will be grateful for your help.

https://community.home-assistant.io/t/philips-air-purifier/53030/161

**Comment by djanosz** [comment]
> > What does your configuration look like, I can't add. second purifier. I will be grateful for your help.
> 
> https://community.home-assistant.io/t/philips-air-purifier/53030/161

Thank you, it works.

**Comment by betaboon** [comment]
@ludipq @barbatron i just released a new version which might also have solved this issue.

if you find the time please test and report back :)

**Comment by ludipq** [comment]
> @ludipq @barbatron i just released a new version which might also have solved this issue.
> 
> if you find the time please test and report back :)

Looks like the update fixed it, but my logs are being spammed with this message every minute:

`
2021-03-21 11:33:14 WARNING (MainThread) [coap] Did not receive requested pktinfo ancdata on message from ('::ffff:192.168.30.18', 5683, 0, 0)`

**Comment by networkpotato** [comment]
Still getting this log spam after upgrading to latest version
