### ISSUE TITLE
AC3829: Initial support

### ISSUE THREAD

**Issue by tenjaa** [betaboon/philips-airpurifier#9]
Hi!
My model is a humidifier too. Is it possible to support it too?
https://www.philips.de/c-p/AC3829_10/series-3000i-2-in-1-kombi-luftreiniger-u.-luftbefeuchter

- Base settings:
`Power: on`
`Humidity: 505`
`Purification & Humidification enabled`
`Light: 100%`
`Fan Speed: Auto`

- Mode: Auto
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "s", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "P", "func": "PH", "rhset": 50, "rh": 48, "temp": 23, "pm25": 1, "iaql": 1, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 207, "fltsts1": 4285, "fltsts2": 4285, "wicksts": 4285, "ota": "ck", "Runtime": 1093551791, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

- Mode: Allergen
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "A", "func": "PH", "rhset": 50, "rh": 48, "temp": 23, "pm25": 2, "iaql": 1, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 206, "fltsts1": 4285, "fltsts2": 4285, "wicksts": 4285, "ota": "ck", "Runtime": 1093725754, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

- Mode: Sleep
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "s", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "S", "func": "PH", "rhset": 50, "rh": 49, "temp": 23, "pm25": 4, "iaql": 1, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 206, "fltsts1": 4285, "fltsts2": 4285, "wicksts": 4285, "ota": "ck", "Runtime": 1093746439, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

Just let me know if you want to need some more information :)

**Comment by betaboon** [comment]
so it might be very similiar to the AC2729. i have not yet implemented the humidifier part, but will do that in the next couple of days.

are there any more speed-settings available in the app in addition to the three that you provided? if so please provide state-data for them :)

**Comment by betaboon** [comment]
could you also provide the available settings for humidity, please?

**Comment by tenjaa** [comment]
Here are the other speed settings. 
`Mode` is disabled and the `Fan Speed` set as stated below.
- Speed 1:
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "M", "func": "PH", "rhset": 50, "rh": 56, "temp": 23, "pm25": 13, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181384972, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

- Speed 2:
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "2", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "M", "func": "PH", "rhset": 50, "rh": 56, "temp": 23, "pm25": 18, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181422250, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`
- Speed 3:
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "3", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "M", "func": "PH", "rhset": 50, "rh": 56, "temp": 23, "pm25": 20, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181441122, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`
- Turbo:
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "t", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "M", "func": "PH", "rhset": 50, "rh": 55, "temp": 23, "pm25": 16, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181458120, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

**Comment by tenjaa** [comment]
- Purification only (everything else to Auto):
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "P", "func": "P", "rhset": 50, "rh": 55, "temp": 23, "pm25": 13, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 0, "wl": 100, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181550247, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

**Comment by tenjaa** [comment]
Purification and Humidification enabled.
- Humidity 40%:
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "P", "func": "PH", "rhset": 40, "rh": 55, "temp": 23, "pm25": 15, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181657108, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`
- Humidity 50%:
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "P", "func": "PH", "rhset": 50, "rh": 55, "temp": 23, "pm25": 14, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181670805, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`
- Humidity 60%:
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "P", "func": "PH", "rhset": 60, "rh": 55, "temp": 23, "pm25": 13, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181689888, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`
- Humidity Max:
`{"name": "Living Room", "type": "AC3829", "modelid": "AC3829/10", "swversion": "1.4.0", "DeviceVersion": "0.0.0", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "dt": 0, "dtrs": 0, "mode": "P", "func": "PH", "rhset": 70, "rh": 56, "temp": 23, "pm25": 13, "iaql": 4, "aqit": 1, "ddp": "0", "rddp": "0", "err": 49408, "wl": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 204, "fltsts1": 4283, "fltsts2": 4283, "wicksts": 4283, "ota": "ck", "Runtime": 1181705381, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "0a5b3b4ef2ac11e8a1e3061302926720", "DeviceId": "c8e0b19ed62f11eab5c6fef2cbffb844", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

**Comment by tenjaa** [comment]
`rh` seems to be the relative humidity read by the device.
`temp` in fact matches with the readings from my thermometer.

**Comment by betaboon** [comment]
@tenjaa i just pushed initial support (speed control only)
could you please test and verify?

**Comment by tenjaa** [comment]
Works like a charm! Nice work!
Anything else you need help with?

**Comment by betaboon** [comment]
i just pushed services for:
- child lock
- display backlight
- light brightness
- humidifier function
- humidity

it would be great if you could test it :)

**Comment by tenjaa** [comment]
>     * child lock
works!
> 
>     * display backlight
works! Technically it is not turning the backlight off. I still see `-` on the screen.
>     * light brightness
works!
>     * humidifier function
works!
>     * humidity
works! Im not sure but maybe it would be cool to enable `purification and humidification` when setting this. With only `purification` enabled this service doesnt do anything
> 
> it would be great if you could test it :)

**Comment by betaboon** [comment]
I'm closing this issue as the initial support for this model seems to be working.

if any new issues arise feel free to open new _dedicated_ issues
